### ISSUE TITLE
Gives memory error

### ISSUE THREAD

**Issue by siddBanPsu** [ray075hl/DeepPhotoStyle_pytorch#1]
Buliding the style transfer model..

> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory

**Comment by ray075hl** [comment]
Hello @siddBanPsu :smile: .
Try small size image as input.
This program really need lots of  device memory. When I test a content image and style image with about size 1000x1000, that consumed about 16GB memory. There must be some ways to modify the code to be memory efficient. For example, release some memory when semantic segmentation finished. But most part of memory is consumed by  intermediate variables at style transfer stage with hard coding. :cry:
PS: My development environment has a CUDA device P40 contain 22GB memory.

**Comment by siddBanPsu** [comment]
Thanks @ray075hl . It worked with a small image. :)
