### ISSUE TITLE
About the weight of different loss items

### ISSUE THREAD

**Issue by hello-trouble** [ray075hl/DeepPhotoStyle_pytorch#12]
Hello , thank  you for your code. I am puzzled about the weight of different loss items.  In our project ,  style_weight=500000, content_weight=100,  tv_weight=0.0001, rl_weight=1.  However,  the weights used in the original paper are   style_weight=100, content_weight=1,  tv_weight=0.0001, rl_weight=10000(photorealism regularization),  How do you choose these hyper-parameters?

**Comment by ray075hl** [comment]
Hello @13462877152 . I think my code may have different detail with official matlab implementation. This weights  choosen by experiments with some pictures.
