### ISSUE TITLE
Torch version

### ISSUE THREAD

**Issue by batuhan3526** [ray075hl/DeepPhotoStyle_pytorch#13]
Hey I created new Env. Then ı used that code. 

conda install pytorch=0.4.1 cuda90 -c pytorch

Then I got this error:
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet

I searched. Everyone says "pls update torch 1.0.0" .But it didnt work and code need 0.4.1 ...

What should ı do ?

**Comment by ray075hl** [comment]
@batuhan3526   
```
pip install torchvision==0.2.2
```

**Comment by batuhan3526** [comment]
thanks you. It worked
