### ISSUE TITLE
还有人在吗？

### ISSUE THREAD

**Issue by tankfly2014** [ray075hl/DeepPhotoStyle_pytorch#2]
没找到你的邮箱试试这里
看起来可以生成一个结果，但是不能导出输出模型吧? 
我想苹果手机上使用这个模型,为什么现在的很多GITHUB产品都不能导出模型呢？这是为什么？我手工能改出来吗？
我是新人，求指教.

**Comment by ray075hl** [comment]
# 保存模型 
``` 
model = MyModel()
# ... after training, save your model 
model.save_state_dict('mytraining.pt')
```
这种风格变换需要根据内容和风格图片进行迭代求解, 保存了模型也没有用啊. 而且需要消耗大量显存, 手机够呛吧

**Comment by tankfly2014** [comment]
多谢
