### ISSUE TITLE
能否提供语义分割模型的百度网盘

### ISSUE THREAD

**Issue by cccusername** [ray075hl/DeepPhotoStyle_pytorch#4]
你好，在sh download_seg_model.sh时无法连接上去，404 not found，可以提供一下百度网盘呢，谢谢了

**Comment by cccusername** [comment]
![无标题](https://user-images.githubusercontent.com/33566026/56010090-c78ac400-5d14-11e9-9316-61b2e9e161b5.png)
model里面的代码没有修改，但是出现了格式的错误，是因为Python版本的问题，请问您用什么版本的Python呢，再次谢谢了

**Comment by ray075hl** [comment]
不用谢 :smile:
版本是python3.6. 
模型我传到google drive上了. 
https://drive.google.com/open?id=1kkeWEQyyLPELBDbxNljEWBn4DBEwP1ZZ

也可以去https://github.com/CSAILVision/semantic-segmentation-pytorch  这里找找, 可能是更新了地址.

**Comment by cccusername** [comment]
谢谢啦
