### ISSUE TITLE
Error when executable download_seg_model.sh script

### ISSUE THREAD

**Issue by FantasyJXF** [ray075hl/DeepPhotoStyle_pytorch#6]
```
The requested URL /model/pytorch/baseline-resnet50_dilated8-ppm_bilinear_deepsup/encoder_epoch_20.pth was not found on this server.
```

The model path is no longer work

**Comment by ray075hl** [comment]
模型我传到google drive上了.
https://drive.google.com/open?id=1kkeWEQyyLPELBDbxNljEWBn4DBEwP1ZZ

也可以去https://github.com/CSAILVision/semantic-segmentation-pytorch 这里找找, 可能是更新了地址.

**Comment by FantasyJXF** [comment]
谢谢
