### ISSUE TITLE
您好，我发现您的权值和论文有些不一样

### ISSUE THREAD

**Issue by cccusername** [ray075hl/DeepPhotoStyle_pytorch#7]
您好，最近在看您的代码时，发现您的损失的权值和论文上的权值有些不一样
`style_weight=1000000, content_weight=100, tv_weight=0.0001, rl_weight=1`
请问您这样设置的原因是什么呢

**Comment by ray075hl** [comment]
看转换的效果决定的, 事实上,每换一对图片, 权重就应该调整.
我记得文献里也说过, 不同的图片对(pair), 并不是使用了相同的权重都会得到最好的结果.

**更重要的是, 可能实现代码的细节不一致, 导致了权值不在一个数量级上, 我是做实验确定这些超参数的, 用原文的参数, 效果不能看......**

**Comment by cccusername** [comment]
好的，感谢您的回答
