### ISSUE TITLE
你好，请问这个错误怎么解决呢

### ISSUE THREAD

**Issue by cccusername** [ray075hl/DeepPhotoStyle_pytorch#8]
![image](https://user-images.githubusercontent.com/33566026/58541140-6750d280-822d-11e9-823e-56932ce64bcc.png)
定位在这里
![image](https://user-images.githubusercontent.com/33566026/58541179-80f21a00-822d-11e9-9e43-6928013d876e.png)
这个guide_image我在Linux上测试时打印出来时没有通道数的，但是同样的代码我在win上测试又是有通道数的，两个平台的opencv版本是一样的

**Comment by ray075hl** [comment]
这个不太清楚, 我只linux下跑过. 
是不是读的灰度图啊?

**Comment by cccusername** [comment]
是读的灰度图，但是在win下面没有问题，Linux上就出错了

**Comment by ray075hl** [comment]
可能是opencv的问题吧.
可以做个判断, 如果图像的维度是2, 就加一维, 再叠三次.

**Comment by cccusername** [comment]
好的，感谢

**Comment by cccusername** [comment]
对了，还是有个问题，
`guide_image = cv2.imread(origin_image_path, -1)`
这里的-1是指读取图片的透明度吗，为什么要把透明的读进来呢，我发后面的代码也是只用到RGB而已

**Comment by ray075hl** [comment]
个人的习惯写法(习惯先读进来原始的数据, 再手动删除alpha),  -1指的是读取未经修改的原始图像
cv2.IMREAD_UNCHANGED : Loads image as such including alpha channel.

**Comment by cccusername** [comment]
我发现直接用默认参数就可以把第三维的参数读进来了，好奇怪。Anyway，还是要谢谢您，回答我这么多小问题哈哈，感谢感谢~
