### ISSUE TITLE
Can you give a "requirments.txt" to show which tools are required and its' version?

### ISSUE THREAD

**Issue by xiaoch1222** [ray075hl/DeepPhotoStyle_pytorch#9]
Can you give a "requirments.txt" to show which tools are required and its' version?

I met a problem of "module 'PIL.Image' has no attribute 'LANCZOS'" which may be caused by PIL version.

**Comment by ray075hl** [comment]
@xiaoch1222  sorry about that. Environment of this project is missed. 
This runtime error may caused by torchvision. I think using anaconda will solve that problem.   
```
conda install pytorch=0.4.1  torchvision cuda90 -c pytorch
```
